groups:
  data_engineers: "data-engineers-dev@example.com"
  data_analysts: "data-analysts-dev@example.com"
  business_users: "business-users-dev@example.com"

gcp:
  project_id: "my-project-dev"
  region: "europe-west1"
  wif_provider: "projects/123456789/locations/global/workloadIdentityPools/github/providers/my-repo"
  terraform_sa: "terraform-sa@my-project-dev.iam.gserviceaccount.com"
  tf_state_bucket: "my-project-dev-tfstate"
